### ISSUE TITLE
JR Built in Functions

### ISSUE THREAD

**Issue by HenryMiller** [richardschoen/ibmijasper#4]
Hello,
It looks like that RTRIM  Built in function is not supported. 
I just added RTRIM to the test EmployeeListing.jrxml file and it fails.
I didn't try other Built in functions.

<img width="994" alt="image" src="https://github.com/user-attachments/assets/7b28bb8a-a38b-4e99-89da-0bd83d753ab6">

<img width="627" alt="image" src="https://github.com/user-attachments/assets/ab67a966-3fb6-4bd5-a16b-4c32650a23bf">

Thank you.
Giovanni

**Comment by richardschoen** [comment]
It would appear this special function was added to Jasper Reports 7.0.  The library used by this package is 6.17.0.

**Comment by HenryMiller** [comment]
Thank you Richard!
